// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgMe6arcCYfiq-QSIl6NTMNF7PJZIPMQY',
    appId: '1:322473331510:web:7a291b7d74301bf8e24197',
    messagingSenderId: '322473331510',
    projectId: 'mapprofect-55188',
    authDomain: 'mapprofect-55188.firebaseapp.com',
    storageBucket: 'mapprofect-55188.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWihjrG_Hr_3SSFjMJljD6U0xW_lnCTa8',
    appId: '1:322473331510:android:e338e1e7b39ddb2ce24197',
    messagingSenderId: '322473331510',
    projectId: 'mapprofect-55188',
    storageBucket: 'mapprofect-55188.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVp75lSj-X5diqqihKeWLnsoqFOAllYq8',
    appId: '1:322473331510:ios:913a4247e976033be24197',
    messagingSenderId: '322473331510',
    projectId: 'mapprofect-55188',
    storageBucket: 'mapprofect-55188.firebasestorage.app',
    iosBundleId: 'com.example.mapProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVp75lSj-X5diqqihKeWLnsoqFOAllYq8',
    appId: '1:322473331510:ios:913a4247e976033be24197',
    messagingSenderId: '322473331510',
    projectId: 'mapprofect-55188',
    storageBucket: 'mapprofect-55188.firebasestorage.app',
    iosBundleId: 'com.example.mapProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgMe6arcCYfiq-QSIl6NTMNF7PJZIPMQY',
    appId: '1:322473331510:web:a3b4ecfeeeb747dfe24197',
    messagingSenderId: '322473331510',
    projectId: 'mapprofect-55188',
    authDomain: 'mapprofect-55188.firebaseapp.com',
    storageBucket: 'mapprofect-55188.firebasestorage.app',
  );
}
